; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
data_dir = src/data
extra_configs = platformio.local.ini

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_speed = 921600
upload_port = COM4       ; ← change to your actual port
monitor_port = COM4      ; ← same port for serial monitor
monitor_speed = 115200
lib_extra_dirs = ~/Documents/Arduino/libraries
board_build.filesystem = littlefs
lib_deps =
    adafruit/Adafruit BMP5xx Library
    adafruit/Adafruit BusIO
    adafruit/Adafruit Unified Sensor
build_flags =
    -D FIRMWARE_VERSION='"1.08"'
    -D OTA_REBOOT_DELAY=5
